### ISSUE TITLE
Allow addition of non-exact matching objects

### ISSUE THREAD

**Issue by EmilyBourne** [Maison-de-la-Simulation/ddc#102]
I think it would be useful to allow expressions such as:
```cpp
ddc::DiscreteElement<Dim1, Dim2> old_pos = ...;
ddc::DiscreteElement<Dim1, Dim2> new_pos = old_pos + ddc::DiscreteVector<Dim2>(3);
```
Currently it is only possible to do:
```cpp
ddc::DiscreteElement<Dim1, Dim2> old_pos = ...;
ddc::DiscreteElement<Dim1, Dim2> new_pos = old_pos + ddc::DiscreteVector<Dim1, Dim2>(3, 0);
```

This addition would be useful in cases where we know that `Dim2` is one of the dimensions but we don't want to specialise the function for all possible values of `Dim1` (present or not present)

**Comment by jbigot** [comment]
I concur :+1:
