### ISSUE TITLE
Use a dedicated branch on gyselalib++ if available for testing

### ISSUE THREAD

**Issue by jbigot** [Maison-de-la-Simulation/ddc#146]

**Comment by tpadioleau** [comment]
You want to test on a branch different from gyselalibxx::main ?

**Comment by jbigot** [comment]
yes, the idea was that if we had a dedicated branch implementing the changes required for the merge, we should test with it. I believe this doesn't apply anymore with the new process, this should be closed

**Comment by tpadioleau** [comment]
ok
