### ISSUE TITLE
DiscreteElement::take() static_assert behaviour

### ISSUE THREAD

**Issue by blegouix** [Maison-de-la-Simulation/ddc#202]
https://github.com/Maison-de-la-Simulation/ddc/blob/ff076238f395653bcff14d9b85d3847f4fd4204c/include/ddc/discrete_element.hpp#L90C5-L92C37

`static_assert(
            !type_seq_contains_v<detail::TypeSeq<HeadTag>, detail::TypeSeq<TailTags...>>,
            "ERROR: tag redundant");`
            
I think the behaviour of this static_assert is not doing what we expect, because it allows two TailTags to be redundant. If QueryTag is the same as HeadTag, the static_assert won't be triggered even if redundant tags are remaining in TailTags.

I propose to allow redundant tags to exist in the DiscreteElements passed as argument of take(), except for QueryTag. It means moving the static_assert inside the `if{}` statement of the function.

**Comment by tpadioleau** [comment]
> I think the behaviour of this static_assert is not doing what we expect, because it allows two TailTags to be redundant. If QueryTag is the same as HeadTag, the static_assert won't be triggered even if redundant tags are remaining in TailTags.

I think you are right.

> I propose to allow redundant tags to exist in the DiscreteElements passed as argument of take(), except for QueryTag. It means moving the static_assert inside the if{} statement of the function.

Yes, can you try that it works ?

**Comment by blegouix** [comment]
It is done in #181, and I checked quickly, the behavior seems correct
