### ISSUE TITLE
Fix benchmark printed error

### ISSUE THREAD

**Issue by tpadioleau** [Maison-de-la-Simulation/ddc#246]
Running the spline benchmark triggers the following error `Kokkos::OpenMP OpenMP instance constructor : ERROR OpenMP is not initialized` because a Kokkos function gets called before its initialization.

It seems to come from a global variable `int par_chunks_per_seq_chunk_ref = Kokkos::OpenMP().concurrency();`

**Comment by blegouix** [comment]
I wait to see if we remove the parallel slicing before solving this or not (if so, the issue disappears)

**Comment by blegouix** [comment]
Not relevant anymore after #247
