### ISSUE TITLE
Clearly distinguish `DiscreteCoordinate`/`DiscreteVector`

### ISSUE THREAD

**Issue by tpadioleau** [Maison-de-la-Simulation/ddc#33]
Issue following issue 41 in the gitlab.

I think we need three types similar to the manipulation of pointers in C++:
- `T*`
- `std::size_t`
- `std::ptrdiff_t`

In our case we would have:
- `DiscreteCoordinate`, identifier of a element of discretization
- `DiscreteSize`, multidimensional size 
- `DiscreteVector`, multidimensional displacement

**Comment by jbigot** [comment]
See also https://gitlab.maisondelasimulation.fr/gysela-developpers/voicexx/-/issues/41

**Comment by jbigot** [comment]
On my side, as discussed, I'm not sure the distinction between `DiscreteSize` & `DiscreteVector`  is easy to do...

**Comment by jbigot** [comment]
on the other hand, `DiscreteCoordinate` behaves more like an array index, which in C++ would be a `size_t`, same as a size

**Comment by tpadioleau** [comment]
I agree, I was also thinking of `to_real(ix)` that would be equivalent to `*ix`. `ix` does not identify a unique array element but it does identify a unique element in the associated discretization.
