### ISSUE TITLE
Rename internal types to match new naming scheme

### ISSUE THREAD

**Issue by tpadioleau** [Maison-de-la-Simulation/ddc#34]
Our types in classes haven't been renamed in the big !73 renaming. For example, we have stuff like:

```
template <class... DDims>
class DiscreteDomain
{
public:
    using mcoord_type = DiscreteCoordinate<DDims...>;
};
```

This should read more like:
```
template <class... DDims>
class DiscreteDomain
{
public:
    using discrete_coordinate_type = DiscreteCoordinate<DDims...>;
};
```

**Comment by jbigot** [comment]
See also https://gitlab.maisondelasimulation.fr/gysela-developpers/voicexx/-/issues/66

**Comment by tpadioleau** [comment]
- to_real -> coordinate, position ?
- DiscreteCoordinate -> DiscreteElement
- DiscreteVector -> ok
- rcoord_type -> c_elem_type, c_element_type, continuous_element_type ?
- dvect_type -> d_vect_type, discrete_vect_type, discrete_vector_type ?
- ddom_type -> d_dom_type, discrete_dom_type, discrete_domain_type ?
- rdim_type -> c_dim_type, c_dimension_type, continuous_dimension_type ?
- mcoord_type -> d_elem_type, d_element_type, discrete_element_type ?
- ddim_type -> d_dim_type, discrete_dim_type, discrete_dimension_type ?

**Comment by tpadioleau** [comment]
- discretization() -> discrete_space() ?

**Comment by jbigot** [comment]
> `discretization()` -> `discrete_space()` ?

:+1:

> `ddim_type` -> `d_dim_type`, `discrete_dim_type`, `discrete_dimension_type` ?

:+1: for `discrete_dimension_type`

> `DiscreteCoordinate` -> `DiscreteElement`

:+1:

> `DiscreteVector` -> ok

:+1:

I'd also propose to change:
* `UniformDiscretization` ->  `UniformPointDiscretization` or `UniformPointSampling`
* `NonUniformDiscretization` ->  `NonUniformPointDiscretization` or `NonUniformPointSampling`

> `dvect_type` -> `d_vect_type`, `discrete_vect_type`, `discrete_vector_type` ?

:+1: for `discrete_vector_type`

> `ddom_type` -> `d_dom_type`, `discrete_dom_type`, `discrete_domain_type` ?

:+1: for `discrete_domain_type`

> `mcoord_type` -> `d_elem_type`, `d_element_type`, `discrete_element_type` ?

:+1: for `discrete_element_type`

> `to_real` -> `coordinate`, `position` ?

:+1: for `coordinate` in case of a `*PointDiscretization`

> `rdim_type` -> `c_dim_type`, `c_dimension_type`, `continuous_dimension_type` ?

:+1: for `continuous_dimension_type` unless we can use different terms for the continuous and discrete cases...

> `rcoord_type` -> `c_elem_type`, `c_element_type`, `continuous_element_type` ?

:+1: for `continuous_element_type`, but maybe we can use `coordinate_type` for an element of a continuous space...

**Comment by tpadioleau** [comment]
As discussed, there may be multiple attributes attached to a discrete coordinate. Some of them can be related to the underlying continous space like in the `UniformPointDiscretization` case. Then should we inject a type such as `continuous_element_type` ?

**Comment by tpadioleau** [comment]
`UniformPointDiscretization` may be closer to the other names we already introduced ?

**Comment by tpadioleau** [comment]
I tried `UniformPointSampling` in the end. Looks good to me.
