### ISSUE TITLE
Public header naming convention

### ISSUE THREAD

**Issue by tpadioleau** [Maison-de-la-Simulation/ddc#6]
Should we have different public headers for the library, with a naming convention, or only a single header like `#include <ddc>`

**Comment by jbigot** [comment]
`ddc.h` ?

**Comment by tpadioleau** [comment]
`ddc.hpp` ? 😄

**Comment by tpadioleau** [comment]
Shall we have an other header for `PDI`, a `ddc/pdi.hpp` ? Or just use a `ifdef` inside `ddc/ddc.hpp` ?

**Comment by jbigot** [comment]
the ifdef solution sounds like the easiest
