### ISSUE TITLE
restrict keyword used as function name

### ISSUE THREAD

**Issue by adegomme** [Maison-de-la-Simulation/ddc#687]
I was trying to compile with nvhpc compilers, and there was an error, which I think could easily be fixed. 
In https://github.com/CExA-project/ddc/commit/5e6a135938c37aa906efc616a42c019c2793780b function intersect_with was renamed to restrict. This causes issues with the nvidia compilers which don't like the "restrict" language keyword to be used for other purposes. 

example of error: 
"/var/tmp/ddc/include/ddc/discrete_domain.hpp", line 176: error: expected a ")"
      KOKKOS_FUNCTION constexpr auto restrict(DiscreteDomain<ODDims...> const& odomain) const

is it possible to rename this function (to its previous name) ?

**Comment by tpadioleau** [comment]
Hi, thank you for reporting this issue. It seems to me completely possible.

That said do we agree that nvhpc is wrong to reserve this keyword ? I mean other compilers usually reserve `__restrict`/`__restrict__` ?

**Comment by adegomme** [comment]
AFAIU, restrict keyword is in the C standard way, but in C++ it's compiler-dependant, as it's not a standard feature. So indeed they should probably have avoided to block a dictionary word, and the others did that. 
The fact that the compiler is unable to properly warn or give a meaningful error message is also a problem, you have to guess.

**Comment by tpadioleau** [comment]
It was pointed to me that, in practice, we should also avoid to use C symbols as some C++ compilers are also able to compile C code. So I am in favor of renaming this function.

Do you need this compiler ? The CI only tests `nvcc` but not `nvhpc`. Unfortunately we do not have runtime tests but we run them manually on Nvidia clusters.
